// src/app/layout.tsx

import './globals.css'; // 1. IMPORT YOUR GLOBAL STYLES (Tailwind & other CSS)
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// 2. CONFIGURE FONT (Next.js automatically handles font optimization)
const inter = Inter({ subsets: ['latin'] });

// 3. DEFINE METADATA (Optional, but recommended for SEO)
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// 4. ROOT LAYOUT COMPONENT
// The 'children' prop will be the content from page.tsx or nested layouts.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* 5. Apply the font class to the body element */}
      <body className={inter.className}>
        {/* The rest of your application content will be rendered here */}
        {children}
      </body>
    </html>
  );
}
